typedef _Bool atomic_bool;
typedef char atomic_char;
typedef signed char atomic_schar;
typedef unsigned char atomic_uchar;
typedef short atomic_short;
typedef unsigned short atomic_ushort;
typedef int atomic_int;
typedef unsigned int atomic_uint;
typedef long atomic_long;
typedef unsigned long atomic_ulong;
typedef long long atomic_llong;
typedef unsigned long long atomic_ullong;
typedef short unsigned int atomic_char16_t;
typedef unsigned int atomic_char32_t;
typedef long int atomic_wchar_t;
typedef signed char atomic_int_least8_t;
typedef unsigned char atomic_uint_least8_t;
typedef short int atomic_int_least16_t;
typedef short unsigned int atomic_uint_least16_t;
typedef int atomic_int_least32_t;
typedef unsigned int atomic_uint_least32_t;
typedef long long int atomic_int_least64_t;
typedef long long unsigned int atomic_uint_least64_t;
typedef signed char atomic_int_fast8_t;
typedef unsigned char atomic_uint_fast8_t;
typedef int atomic_int_fast16_t;
typedef unsigned int atomic_uint_fast16_t;
typedef int atomic_int_fast32_t;
typedef unsigned int atomic_uint_fast32_t;
typedef long long int atomic_int_fast64_t;
typedef long long unsigned int atomic_uint_fast64_t;
typedef int atomic_intptr_t;
typedef unsigned int atomic_uintptr_t;
typedef unsigned int atomic_size_t;
typedef int atomic_ptrdiff_t;
typedef long long int atomic_intmax_t;
typedef long long unsigned int atomic_uintmax_t;
